foreground           #ffff00
background           #1a1a1a
selection_foreground #000000
selection_background #ffff00
cursor               #ffff00
cursor_text_color    #111111

font_family      RuneScape UF
bold_font        auto
italic_font      auto
bold_italic_font auto
font_size        22.0

background_opacity         0.85
dynamic_background_opacity yes
confirm_os_window_close    0

cursor_shape          block
shell_integration     no-cursor
cursor_trail          1
cursor_trail_decay    0.1 0.4

window_padding_width  10
linux_display_server  auto

scrollback_lines      2000
wheel_scroll_min_lines 1

enable_audio_bell     no

active_tab_foreground   #1a1a1a
active_tab_background   #ffff00
inactive_tab_foreground #ffff00
inactive_tab_background #333333