
font_family      RuneScape UF
font_size        16.0
bold_font        auto
italic_font      auto
bold_italic_font auto

background       #1a1914 
foreground       #ffffff 

cursor           #ffff00
cursor_shape     block
selection_background #ffff00
selection_foreground #1a1914

background_opacity         0.9
dynamic_background_opacity 1
confirm_os_window_close    0
window_padding_width       12

cursor_trail       1
linux_display_server   auto
scrollback_lines       2000
wheel_scroll_min_lines 1
enable_audio_bell      no