general {
    no_fade_in = false
    grace = 0
    disable_loading_bar = true
    hide_cursor = true
}
background {
    monitor =
    # Ensure this file exists, or change path to "screenshot"
    path = ~/.config/hypr/osrs.png 
    color = rgb(30, 26, 19)
    blur_passes = 0 
}
shape {
    monitor =
    size = 400, 280
    color = rgba(62, 53, 41, 0.9) # OSRS Brown
    rounding = 0 # Square corners for that old-school feel
    border_size = 4
    border_color = rgb(30, 26, 19) # Darker trim
    position = 0, 0
    halign = center
    valign = center
}
label {
    monitor =
    text = Sit Rat
    color = rgb(255, 255, 0)
    font_size = 40
    font_family = RuneScape UF
    position = 0, 80
    halign = center
    valign = center
}
label {
    monitor =
    text = Enter your password to play.
    color = rgb(255, 255, 255)
    font_size = 16
    font_family = RuneScape UF
    position = 0, 30
    halign = center
    valign = center
}

input-field {
    monitor =
    size = 280, 50
    outline_thickness = 3
    outer_color = rgb(30, 26, 19)
    inner_color = rgb(77, 68, 56)
    font_color = rgb(255, 255, 0)
    dots_size = 0.33 
    dots_spacing = 0.15
    dots_center = true
    fade_on_empty = false
    placeholder_text = <span font_family="RuneScape UF" foreground="##ffff00">Enter Password</span>
    check_color = rgb(255, 255, 255)
    fail_color = rgb(255, 0, 0)
    fail_text = <span font_family="RuneScape UF">Invalid Password.</span>
    position = 0, -50
    halign = center
    valign = center
}
label {
    monitor =
    text = (click here to cancel)
    color = rgb(255, 255, 255)
    font_size = 10
    font_family = RuneScape UF
    position = 0, -110
    halign = center
    valign = center
}
