# #######################################################################################
# OSRS THEMED HYPRLAND CONFIG - WELCOME TO GIELINOR
# #######################################################################################

# Theme: RuneScape Classic / OSRS
# Primary Colors: 
# Gold: rgba(ffbb00ee) | Slate: rgba(3e3e3eaa) | Bank-interface: rgba(4d4232ee)

# These will be unique to your env make sure to review apps and put your own execs
exec = gsettings set org.gnome.desktop.interface color-scheme "prefer-dark"
exec = gsettings set org.gnome.desktop.interface gtk-theme "adw-gtk3"
exec-once = waypaper --restore
exec-once = dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP=Hyprland
exec-once=/usr/lib/hyprpolkitagent/hyprpolkitagent
env = QT_QPA_PLATFORMTHEME,qt6ct
# This starts the password popup agent
exec-once = /usr/lib/polkit-kde-authentication-agent-1
xwayland {
  force_zero_scaling = true
}
monitor=,preferred,auto,auto

# Change to tools you prefer
$terminal = kitty
$fileManager = dolphin
$menu = rofi -show run -theme ~/.config/rofi/osrs.rasi
$lock = hyprlock
$wallpaper = waypaper

# On logon once
exec-once = $terminal
exec-once = waybar & hyprpaper
env = XCURSOR_SIZE,24
env = HYPRCURSOR_SIZE,24

## All look and feels
general {
    gaps_in = 4
    gaps_out = 12
    border_size = 3
    col.active_border = rgba(3e3529ee) 
    col.inactive_border = rgba(24201aaa)
    resize_on_border = true
    allow_tearing = false
    layout = dwindle
}
decoration {
    rounding = 2
    active_opacity = 1.0
    inactive_opacity = 0.9
    shadow {
        enabled = true
        range = 10
        render_power = 2
        color = rgba(050505ee)
    }
    blur {
        enabled = true
        size = 5
        passes = 2
        vibrancy = 0.1
    }
}

animations {
    enabled = yes
    bezier = osrsTick, 0.05, 0.9, 0.1, 1.05
    animation = windows, 1, 3, osrsTick
    animation = windowsOut, 1, 3, default, popin 80%
    animation = border, 1, 2, default
    animation = fade, 1, 4, default
    animation = workspaces, 1, 3, osrsTick, slide
}
dwindle {
    pseudotile = true
    preserve_split = true
}
misc {
    force_default_wallpaper = 0
    disable_hyprland_logo = true
    background_color = rgba(1a1a1aff)
}
input {
    kb_layout = us
    follow_mouse = 1
    sensitivity = 0 
    touchpad {
        natural_scroll = false
    }
}
## Customise keybindings to what you prefer.
$mainMod = SUPER
bind = SUPER_SHIFT, S, exec, grim -g "$(slurp)" - | wl-copy
bind = $mainMod, W, exec, $wallpaper
bind = $mainMod, L, exec, $lock
bind = $mainMod, return, exec, $terminal
bind = $mainMod, D, exec, $menu
bind = $mainMod, B, exec, firefox
bind = $mainMod, Q, killactive,
bind = $mainMod, E, exec, $fileManager
bind = $mainMod, V, togglefloating,
bind = $mainMod, R, exec, $menu
bind = $mainMod, F, fullscreen,

# Switch workspaces
bind = $mainMod, 1, workspace, 1
bind = $mainMod, 2, workspace, 2
bind = $mainMod, 3, workspace, 3
bind = $mainMod, 4, workspace, 4
bind = $mainMod, 5, workspace, 5
bind = $mainMod, 6, workspace, 6

# Move windows across workspaces
bind = $mainMod SHIFT, 1, movetoworkspace, 1
bind = $mainMod SHIFT, 2, movetoworkspace, 2
bind = $mainMod SHIFT, 3, movetoworkspace, 3
bind = $mainMod SHIFT, 4, movetoworkspace, 4
bind = $mainMod SHIFT, 5, movetoworkspace, 5
bind = $mainMod SHIFT, 6, movetoworkspace, 6
bind = $mainMod SHIFT, 7, movetoworkspace, 7
bind = $mainMod SHIFT, 8, movetoworkspace, 8
bind = $mainMod SHIFT, 9, movetoworkspace, 9

# Mouse binds
bindm = $mainMod, mouse:272, movewindow
bindm = $mainMod, mouse:273, resizewindow

# No Full Screen (feel free to modify this)
windowrule {
    name = suppress-maximize-events
    match:class = .*
    suppress_event = maximize
}
